# Definir el tamaño de la pantalla
ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60

# Constantes de salud y dinero
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = 2

# Constantes de enemigos
SPAWN_COOLDOWN = 400

#Constantes de torres
TURRET_LEVELS = 4
BUY_COST = 200
UPGRADE_COST = 100
KILL_REWARD = 10
LEVEL_COMPLETE_REWARD = 100
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
DAMAGE = 5